version: '3.8'

services:
  # postgresql:
  #   image: postgre:latest
  #   restart: unless-stopped
  #   env_file: ./.env
  backend: 
    env_file: 
      - ./server/.env
    container_name: backend
    build: 
      dockerfile: ./server/Dockerfile
      context: .
      target: dev
    volumes:
      - .:/app
    environment:
      APP_PORT: "${APP_PORT}"
    ports: 
      - "${APP_PORT}:${APP_PORT}"

